version: '3.8'

services:
  neo4j:
    build: 
      context: .
      dockerfile: Dockerfile.neo4j
    container_name: neo4j-apoc-container
    environment:
      - NEO4J_AUTH=neo4j/securepassword123
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc"]
    ports:
      - "7474:7474"  # Neo4j browser
      - "7687:7687"  # Bolt protocol (Neo4j client connections)
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./import:/var/lib/neo4j/import
      - ./plugins:/plugins
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
