FROM neo4j:latest

ENV NEO4J_apoc_export_file_enabled=true
ENV NEO4J_apoc_import_file_enabled=true
ENV NEO4J_apoc_import_file_use__neo4j__config=true

ENV NEO4JLABS_PLUGINS '["apoc"]'

EXPOSE 7474 7687
